name: Two Jobs Workflow

on:
  push:
    branches:
      - master

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Add your job1 steps here

  job2:
    needs: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print Job1 status
        run: echo "Job1 status: ${{ job.status }}"

      # Add your job2 steps here
